# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bill' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod 'RealmSwift', '~> 3.6.0'
pod 'Alamofire', '~> 4.7.2'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'SnapKit', '~> 4.0.0'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'Charts', '~> 3.1.1'


  # Pods for Bill

end
